core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/', include("todo.urls"))

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todo/urls.py
from django.urls import path
from .views import *

app_name = 'todo'

urlpatterns = [
    path('index/', myview, name='index'),
    path('add/', add_view, name='add'),
]

todo/models.py
from django.db import models
from services.generator import Generator
from services.mixin import SlugMixin

class Todo(SlugMixin):
    task_name = models.CharField(max_length=200)
    deadline = models.DateField(null=True, blank=True)
    status = models.BooleanField(null=True, blank=True)

    class Meta:
        verbose_name = 'Todo'
        verbose_name_plural = 'Todo Lists'

    def __str__(self):
        return self.task_name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = Generator.create_slug_shortcode(size=15, model_=Todo)
        super(Todo, self).save(*args, **kwargs)

todo/forms.py
from .models import Todo
from django import forms


class ToDoForm(forms.ModelForm):
    class Meta:
        model = Todo
        exclude = ('status',)

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Todo
from .forms import *
from django.contrib import messages


def myview(request):
    context = {}
    obj = Todo.objects.all()

    if "all" in request.GET:
        all = request.GET.get('all')
        obj = Todo.objects.all()

    if "on" in request.GET:
        obj = obj.filter(
            status=True
        )

    if "off" in request.GET:
        obj = obj.filter(
            status=False
        )

    bt = request.GET.get('bt', None)
    at = request.GET.get('at', None)
    if bt:
        obj = obj.filter(
            deadline__gte=bt
        )

    if at:
        obj = obj.filter(
            deadline__lte=at
        )

    print(request.GET)
    context['todos'] = obj
    return render(request, 'index.html', context)


def add_view(request):
    context = {}
    form = ToDoForm()
    if request.method == "POST":
        form = ToDoForm(request.POST or None)
        if form.is_valid():
            new_task = form.save()
            messages.success(request, f"{new_task.task_name} added!")
            return redirect("todo:add")

    context['form'] = form
    return render(request, 'add.html', context)

templates/add.html
<!doctype html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Add page</title>
</head>
<body>


        {% if messages %}
        {% for message in messages %}

        <div class="alert alert-{{ message.tags }}" role="alert">

          {{ message }}
        </div>
        {% endfor %}
    {% endif %}

        {% if form.errors %}
                                        <div class="error-message mb-4">
                                                {% for field in form %}
                                                    {% for error in field.errors %}
                                                        <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                    {% endfor %}
                                                {% endfor %}
                                                {% for error in form.non_field_errors %}
                                                    <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                {% endfor %}
                                        </div>
                                {% endif %}




<h1>SALAAAM</h1>

<form method="post">
    {% csrf_token %}
    {% for i in form %}
    {{i.label}}  {{ i }} <br>
    {% endfor %}
    <button type="submit">Submit</button>

</form>

<p><a href="{% url 'todo:index' %}">Siyahi ucun klikle</a></p>




</body>
</html>

templates/index.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>To-do List</title>
</head>
<body>

<p><a href="{% url 'todo:add' %}">Add task for this</a></p>


<form>


<p>
    <input type="checkbox" value="all" name="all"> All
</p>
<p>
    <input type="checkbox" name="on" value="{{status.id}}"> Completed
</p>
<p>
    <input type="checkbox" name="off" value="{{status.id}}"> Uncompleted
</p>

<p>
    <input type="text" placeholder="YYYY-MM-DD"  name="bt"> before
</p>
    <p>
    <input type="text" placeholder="YYYY-MM-DD" name="at"> after
</p>
    <button type="submit" class="btn btn-success">Filter</button>

</form>







<div style="display: flex; align-items: center; justify-content: center; margin-top: 150px;" class="data">


    {% for i in todos %}

    <div style="border: 1px solid gray">
        <input type="checkbox" {% if i.status %} checked  {% endif %}><span class="text-danger"><a href="#">X</a></span>{{i.task_name}}
    </div>
    <div></div>
    {% endfor %}


</div>

</body>
</html>

templates/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Update Page</title>
</head>


{% if messages %}
        {% for message in messages %}

        <div class="alert alert-{{ message.tags }}" role="alert">

          {{ message }}
        </div>
        {% endfor %}
    {% endif %}

    {% if form.errors %}
                                        <div class="error-message mb-4">
                                                {% for field in form %}
                                                    {% for error in field.errors %}
                                                        <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                    {% endfor %}
                                                {% endfor %}
                                                {% for error in form.non_field_errors %}
                                                    <div class="alert alert-danger" role="alert">
                                                              {{ error|escape }}
                                                            </div>
                                                {% endfor %}
                                        </div>
                                {% endif %}

















<body>
            <input type="hidden" name="delete_image_ids" id="delete_image_ids">

<form>


<p>
    <input type="checkbox" value="all" name="all"> All
</p>
<p>
    <input type="checkbox" name="on" value="{{status.id}}"> Completed
</p>
<p>
    <input type="checkbox" name="off" value="{{status.id}}"> Uncompleted
</p>

<p>
    <input type="text" placeholder="YYYY-MM-DD"  name="bt"> before
</p>
    <p>
    <input type="text" placeholder="YYYY-MM-DD" name="at"> after
</p>
    <button type="submit" class="btn btn-success">Filter</button>

</form>







<div style="display: flex; align-items: center; justify-content: center; margin-top: 150px;" class="data">


    {% for i in todos %}

    <div style="border: 1px solid gray">
        <input type="checkbox" {% if i.status %} checked  {% endif %}><span class="text-danger"><a href="#">X</a></span>{{i.task_name}}
    </div>
    <div></div>
    {% endfor %}


</div>









</body>
</html>